# Generated by Django 3.2.9 on 2021-12-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20211206_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='value',
            new_name='amount',
        ),
    ]
