# Generated by Django 3.2.9 on 2021-12-22 17:11

from django.db import migrations, models

import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[recipes.validators.cooking_time_amount_validator], verbose_name='Время приготовления'),
        ),
    ]
